// Generated by gencpp from file detection_msgs/StringArray.msg
// DO NOT EDIT!


#ifndef DETECTION_MSGS_MESSAGE_STRINGARRAY_H
#define DETECTION_MSGS_MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection_msgs
{
template <class ContainerAllocator>
struct StringArray_
{
  typedef StringArray_<ContainerAllocator> Type;

  StringArray_()
    : strings()  {
    }
  StringArray_(const ContainerAllocator& _alloc)
    : strings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _strings_type;
  _strings_type strings;





  typedef boost::shared_ptr< ::detection_msgs::StringArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection_msgs::StringArray_<ContainerAllocator> const> ConstPtr;

}; // struct StringArray_

typedef ::detection_msgs::StringArray_<std::allocator<void> > StringArray;

typedef boost::shared_ptr< ::detection_msgs::StringArray > StringArrayPtr;
typedef boost::shared_ptr< ::detection_msgs::StringArray const> StringArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection_msgs::StringArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection_msgs::StringArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detection_msgs::StringArray_<ContainerAllocator1> & lhs, const ::detection_msgs::StringArray_<ContainerAllocator2> & rhs)
{
  return lhs.strings == rhs.strings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detection_msgs::StringArray_<ContainerAllocator1> & lhs, const ::detection_msgs::StringArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detection_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detection_msgs::StringArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_msgs::StringArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_msgs::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_msgs::StringArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_msgs::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_msgs::StringArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51789d20146e565223d0963361aecda1";
  }

  static const char* value(const ::detection_msgs::StringArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51789d20146e5652ULL;
  static const uint64_t static_value2 = 0x23d0963361aecda1ULL;
};

template<class ContainerAllocator>
struct DataType< ::detection_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection_msgs/StringArray";
  }

  static const char* value(const ::detection_msgs::StringArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] strings\n"
;
  }

  static const char* value(const ::detection_msgs::StringArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection_msgs::StringArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.strings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection_msgs::StringArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection_msgs::StringArray_<ContainerAllocator>& v)
  {
    s << indent << "strings[]" << std::endl;
    for (size_t i = 0; i < v.strings.size(); ++i)
    {
      s << indent << "  strings[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.strings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_MSGS_MESSAGE_STRINGARRAY_H
