// Generated by gencpp from file human_msgs/HumanTwistArray.msg
// DO NOT EDIT!


#ifndef HUMAN_MSGS_MESSAGE_HUMANTWISTARRAY_H
#define HUMAN_MSGS_MESSAGE_HUMANTWISTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <human_msgs/HumanTwist.h>

namespace human_msgs
{
template <class ContainerAllocator>
struct HumanTwistArray_
{
  typedef HumanTwistArray_<ContainerAllocator> Type;

  HumanTwistArray_()
    : header()
    , twists()  {
    }
  HumanTwistArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , twists(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::human_msgs::HumanTwist_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::human_msgs::HumanTwist_<ContainerAllocator> >> _twists_type;
  _twists_type twists;





  typedef boost::shared_ptr< ::human_msgs::HumanTwistArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_msgs::HumanTwistArray_<ContainerAllocator> const> ConstPtr;

}; // struct HumanTwistArray_

typedef ::human_msgs::HumanTwistArray_<std::allocator<void> > HumanTwistArray;

typedef boost::shared_ptr< ::human_msgs::HumanTwistArray > HumanTwistArrayPtr;
typedef boost::shared_ptr< ::human_msgs::HumanTwistArray const> HumanTwistArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_msgs::HumanTwistArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_msgs::HumanTwistArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_msgs::HumanTwistArray_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTwistArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.twists == rhs.twists;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_msgs::HumanTwistArray_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTwistArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTwistArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTwistArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTwistArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07265c7c8f0288cacbbba8ea359ddf7f";
  }

  static const char* value(const ::human_msgs::HumanTwistArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07265c7c8f0288caULL;
  static const uint64_t static_value2 = 0xcbbba8ea359ddf7fULL;
};

template<class ContainerAllocator>
struct DataType< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_msgs/HumanTwistArray";
  }

  static const char* value(const ::human_msgs::HumanTwistArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"HumanTwist[]    twists\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: human_msgs/HumanTwist\n"
"uint64              id\n"
"geometry_msgs/Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::human_msgs::HumanTwistArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.twists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanTwistArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_msgs::HumanTwistArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_msgs::HumanTwistArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "twists[]" << std::endl;
    for (size_t i = 0; i < v.twists.size(); ++i)
    {
      s << indent << "  twists[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::human_msgs::HumanTwist_<ContainerAllocator> >::stream(s, indent + "    ", v.twists[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_MSGS_MESSAGE_HUMANTWISTARRAY_H
