// Generated by gencpp from file human_msgs/HumanTimeToGoalArray.msg
// DO NOT EDIT!


#ifndef HUMAN_MSGS_MESSAGE_HUMANTIMETOGOALARRAY_H
#define HUMAN_MSGS_MESSAGE_HUMANTIMETOGOALARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <human_msgs/HumanTimeToGoal.h>

namespace human_msgs
{
template <class ContainerAllocator>
struct HumanTimeToGoalArray_
{
  typedef HumanTimeToGoalArray_<ContainerAllocator> Type;

  HumanTimeToGoalArray_()
    : header()
    , times_to_goal()  {
    }
  HumanTimeToGoalArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , times_to_goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >> _times_to_goal_type;
  _times_to_goal_type times_to_goal;





  typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> const> ConstPtr;

}; // struct HumanTimeToGoalArray_

typedef ::human_msgs::HumanTimeToGoalArray_<std::allocator<void> > HumanTimeToGoalArray;

typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoalArray > HumanTimeToGoalArrayPtr;
typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoalArray const> HumanTimeToGoalArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.times_to_goal == rhs.times_to_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ede5186f8390c247effec1c7d29fe0f";
  }

  static const char* value(const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ede5186f8390c24ULL;
  static const uint64_t static_value2 = 0x7effec1c7d29fe0fULL;
};

template<class ContainerAllocator>
struct DataType< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_msgs/HumanTimeToGoalArray";
  }

  static const char* value(const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header             header\n"
"human_msgs/HumanTimeToGoal[] times_to_goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: human_msgs/HumanTimeToGoal\n"
"std_msgs/Header header\n"
"uint64          id\n"
"duration        time_to_goal\n"
;
  }

  static const char* value(const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.times_to_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanTimeToGoalArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_msgs::HumanTimeToGoalArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "times_to_goal[]" << std::endl;
    for (size_t i = 0; i < v.times_to_goal.size(); ++i)
    {
      s << indent << "  times_to_goal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >::stream(s, indent + "    ", v.times_to_goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_MSGS_MESSAGE_HUMANTIMETOGOALARRAY_H
