// Generated by gencpp from file human_msgs/HumanTwist.msg
// DO NOT EDIT!


#ifndef HUMAN_MSGS_MESSAGE_HUMANTWIST_H
#define HUMAN_MSGS_MESSAGE_HUMANTWIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace human_msgs
{
template <class ContainerAllocator>
struct HumanTwist_
{
  typedef HumanTwist_<ContainerAllocator> Type;

  HumanTwist_()
    : id(0)
    , twist()  {
    }
  HumanTwist_(const ContainerAllocator& _alloc)
    : id(0)
    , twist(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;





  typedef boost::shared_ptr< ::human_msgs::HumanTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_msgs::HumanTwist_<ContainerAllocator> const> ConstPtr;

}; // struct HumanTwist_

typedef ::human_msgs::HumanTwist_<std::allocator<void> > HumanTwist;

typedef boost::shared_ptr< ::human_msgs::HumanTwist > HumanTwistPtr;
typedef boost::shared_ptr< ::human_msgs::HumanTwist const> HumanTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_msgs::HumanTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_msgs::HumanTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_msgs::HumanTwist_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTwist_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.twist == rhs.twist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_msgs::HumanTwist_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTwist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTwist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_msgs::HumanTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a13f6dfa6e5d280c2d013ce807ed0b9";
  }

  static const char* value(const ::human_msgs::HumanTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a13f6dfa6e5d280ULL;
  static const uint64_t static_value2 = 0xc2d013ce807ed0b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::human_msgs::HumanTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_msgs/HumanTwist";
  }

  static const char* value(const ::human_msgs::HumanTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_msgs::HumanTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64              id\n"
"geometry_msgs/Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::human_msgs::HumanTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_msgs::HumanTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_msgs::HumanTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_msgs::HumanTwist_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_MSGS_MESSAGE_HUMANTWIST_H
