// Generated by gencpp from file human_msgs/TrackedHuman.msg
// DO NOT EDIT!


#ifndef HUMAN_MSGS_MESSAGE_TRACKEDHUMAN_H
#define HUMAN_MSGS_MESSAGE_TRACKEDHUMAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <human_msgs/TrackedSegment.h>

namespace human_msgs
{
template <class ContainerAllocator>
struct TrackedHuman_
{
  typedef TrackedHuman_<ContainerAllocator> Type;

  TrackedHuman_()
    : track_id(0)
    , state(0)
    , segments()  {
    }
  TrackedHuman_(const ContainerAllocator& _alloc)
    : track_id(0)
    , state(0)
    , segments(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _track_id_type;
  _track_id_type track_id;

   typedef int8_t _state_type;
  _state_type state;

   typedef std::vector< ::human_msgs::TrackedSegment_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::human_msgs::TrackedSegment_<ContainerAllocator> >> _segments_type;
  _segments_type segments;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATIC)
  #undef STATIC
#endif
#if defined(_WIN32) && defined(MOVING)
  #undef MOVING
#endif
#if defined(_WIN32) && defined(STOPPED)
  #undef STOPPED
#endif
#if defined(_WIN32) && defined(BLOCKED)
  #undef BLOCKED
#endif

  enum {
    STATIC = 0,
    MOVING = 1,
    STOPPED = 2,
    BLOCKED = 3,
  };


  typedef boost::shared_ptr< ::human_msgs::TrackedHuman_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_msgs::TrackedHuman_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedHuman_

typedef ::human_msgs::TrackedHuman_<std::allocator<void> > TrackedHuman;

typedef boost::shared_ptr< ::human_msgs::TrackedHuman > TrackedHumanPtr;
typedef boost::shared_ptr< ::human_msgs::TrackedHuman const> TrackedHumanConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_msgs::TrackedHuman_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_msgs::TrackedHuman_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_msgs::TrackedHuman_<ContainerAllocator1> & lhs, const ::human_msgs::TrackedHuman_<ContainerAllocator2> & rhs)
{
  return lhs.track_id == rhs.track_id &&
    lhs.state == rhs.state &&
    lhs.segments == rhs.segments;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_msgs::TrackedHuman_<ContainerAllocator1> & lhs, const ::human_msgs::TrackedHuman_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_msgs::TrackedHuman_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_msgs::TrackedHuman_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::TrackedHuman_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::TrackedHuman_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::TrackedHuman_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::TrackedHuman_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_msgs::TrackedHuman_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6137b5ecce7d20cb2b1e3c938818307c";
  }

  static const char* value(const ::human_msgs::TrackedHuman_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6137b5ecce7d20cbULL;
  static const uint64_t static_value2 = 0x2b1e3c938818307cULL;
};

template<class ContainerAllocator>
struct DataType< ::human_msgs::TrackedHuman_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_msgs/TrackedHuman";
  }

  static const char* value(const ::human_msgs::TrackedHuman_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_msgs::TrackedHuman_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# states\n"
"int8 STATIC=0\n"
"int8 MOVING=1\n"
"int8 STOPPED=2\n"
"int8 BLOCKED=3\n"
"\n"
"uint64              track_id\n"
"int8                state\n"
"TrackedSegment[]    segments\n"
"\n"
"================================================================================\n"
"MSG: human_msgs/TrackedSegment\n"
"int8                                type\n"
"geometry_msgs/PoseWithCovariance    pose\n"
"geometry_msgs/TwistWithCovariance   twist\n"
"geometry_msgs/AccelWithCovariance   accel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/AccelWithCovariance\n"
"# This expresses acceleration in free space with uncertainty.\n"
"\n"
"Accel accel\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
;
  }

  static const char* value(const ::human_msgs::TrackedHuman_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_msgs::TrackedHuman_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.track_id);
      stream.next(m.state);
      stream.next(m.segments);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedHuman_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_msgs::TrackedHuman_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_msgs::TrackedHuman_<ContainerAllocator>& v)
  {
    s << indent << "track_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.track_id);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "segments[]" << std::endl;
    for (size_t i = 0; i < v.segments.size(); ++i)
    {
      s << indent << "  segments[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::human_msgs::TrackedSegment_<ContainerAllocator> >::stream(s, indent + "    ", v.segments[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_MSGS_MESSAGE_TRACKEDHUMAN_H
