// Generated by gencpp from file pedsim_srvs/GymResetRequest.msg
// DO NOT EDIT!


#ifndef PEDSIM_SRVS_MESSAGE_GYMRESETREQUEST_H
#define PEDSIM_SRVS_MESSAGE_GYMRESETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pedsim_msgs/GymAgentInfo.h>

namespace pedsim_srvs
{
template <class ContainerAllocator>
struct GymResetRequest_
{
  typedef GymResetRequest_<ContainerAllocator> Type;

  GymResetRequest_()
    : agents_list()  {
    }
  GymResetRequest_(const ContainerAllocator& _alloc)
    : agents_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >> _agents_list_type;
  _agents_list_type agents_list;





  typedef boost::shared_ptr< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GymResetRequest_

typedef ::pedsim_srvs::GymResetRequest_<std::allocator<void> > GymResetRequest;

typedef boost::shared_ptr< ::pedsim_srvs::GymResetRequest > GymResetRequestPtr;
typedef boost::shared_ptr< ::pedsim_srvs::GymResetRequest const> GymResetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pedsim_srvs::GymResetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pedsim_srvs::GymResetRequest_<ContainerAllocator1> & lhs, const ::pedsim_srvs::GymResetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.agents_list == rhs.agents_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pedsim_srvs::GymResetRequest_<ContainerAllocator1> & lhs, const ::pedsim_srvs::GymResetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pedsim_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9abbb83c72232af33703953db3d87b22";
  }

  static const char* value(const ::pedsim_srvs::GymResetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9abbb83c72232af3ULL;
  static const uint64_t static_value2 = 0x3703953db3d87b22ULL;
};

template<class ContainerAllocator>
struct DataType< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pedsim_srvs/GymResetRequest";
  }

  static const char* value(const ::pedsim_srvs::GymResetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pedsim_msgs/GymAgentInfo[] agents_list\n"
"\n"
"================================================================================\n"
"MSG: pedsim_msgs/GymAgentInfo\n"
"geometry_msgs/Pose2D    init_pose2d\n"
"geometry_msgs/Pose2D[]  waypoints_list\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::pedsim_srvs::GymResetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agents_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GymResetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pedsim_srvs::GymResetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pedsim_srvs::GymResetRequest_<ContainerAllocator>& v)
  {
    s << indent << "agents_list[]" << std::endl;
    for (size_t i = 0; i < v.agents_list.size(); ++i)
    {
      s << indent << "  agents_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.agents_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEDSIM_SRVS_MESSAGE_GYMRESETREQUEST_H
