// Generated by gencpp from file walker_msgs/PushingActionTrigger.msg
// DO NOT EDIT!


#ifndef WALKER_MSGS_MESSAGE_PUSHINGACTIONTRIGGER_H
#define WALKER_MSGS_MESSAGE_PUSHINGACTIONTRIGGER_H

#include <ros/service_traits.h>


#include <walker_msgs/PushingActionTriggerRequest.h>
#include <walker_msgs/PushingActionTriggerResponse.h>


namespace walker_msgs
{

struct PushingActionTrigger
{

typedef PushingActionTriggerRequest Request;
typedef PushingActionTriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PushingActionTrigger
} // namespace walker_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::walker_msgs::PushingActionTrigger > {
  static const char* value()
  {
    return "91c2eaf71113b433d55580921476f329";
  }

  static const char* value(const ::walker_msgs::PushingActionTrigger&) { return value(); }
};

template<>
struct DataType< ::walker_msgs::PushingActionTrigger > {
  static const char* value()
  {
    return "walker_msgs/PushingActionTrigger";
  }

  static const char* value(const ::walker_msgs::PushingActionTrigger&) { return value(); }
};


// service_traits::MD5Sum< ::walker_msgs::PushingActionTriggerRequest> should match
// service_traits::MD5Sum< ::walker_msgs::PushingActionTrigger >
template<>
struct MD5Sum< ::walker_msgs::PushingActionTriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::walker_msgs::PushingActionTrigger >::value();
  }
  static const char* value(const ::walker_msgs::PushingActionTriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::walker_msgs::PushingActionTriggerRequest> should match
// service_traits::DataType< ::walker_msgs::PushingActionTrigger >
template<>
struct DataType< ::walker_msgs::PushingActionTriggerRequest>
{
  static const char* value()
  {
    return DataType< ::walker_msgs::PushingActionTrigger >::value();
  }
  static const char* value(const ::walker_msgs::PushingActionTriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::walker_msgs::PushingActionTriggerResponse> should match
// service_traits::MD5Sum< ::walker_msgs::PushingActionTrigger >
template<>
struct MD5Sum< ::walker_msgs::PushingActionTriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::walker_msgs::PushingActionTrigger >::value();
  }
  static const char* value(const ::walker_msgs::PushingActionTriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::walker_msgs::PushingActionTriggerResponse> should match
// service_traits::DataType< ::walker_msgs::PushingActionTrigger >
template<>
struct DataType< ::walker_msgs::PushingActionTriggerResponse>
{
  static const char* value()
  {
    return DataType< ::walker_msgs::PushingActionTrigger >::value();
  }
  static const char* value(const ::walker_msgs::PushingActionTriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WALKER_MSGS_MESSAGE_PUSHINGACTIONTRIGGER_H
