// Generated by gencpp from file walker_msgs/Trk3DArray.msg
// DO NOT EDIT!


#ifndef WALKER_MSGS_MESSAGE_TRK3DARRAY_H
#define WALKER_MSGS_MESSAGE_TRK3DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <walker_msgs/Trk3D.h>
#include <sensor_msgs/LaserScan.h>

namespace walker_msgs
{
template <class ContainerAllocator>
struct Trk3DArray_
{
  typedef Trk3DArray_<ContainerAllocator> Type;

  Trk3DArray_()
    : header()
    , trks_list()
    , scan()  {
    }
  Trk3DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , trks_list(_alloc)
    , scan(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::walker_msgs::Trk3D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::walker_msgs::Trk3D_<ContainerAllocator> >> _trks_list_type;
  _trks_list_type trks_list;

   typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _scan_type;
  _scan_type scan;





  typedef boost::shared_ptr< ::walker_msgs::Trk3DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walker_msgs::Trk3DArray_<ContainerAllocator> const> ConstPtr;

}; // struct Trk3DArray_

typedef ::walker_msgs::Trk3DArray_<std::allocator<void> > Trk3DArray;

typedef boost::shared_ptr< ::walker_msgs::Trk3DArray > Trk3DArrayPtr;
typedef boost::shared_ptr< ::walker_msgs::Trk3DArray const> Trk3DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::walker_msgs::Trk3DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::walker_msgs::Trk3DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::walker_msgs::Trk3DArray_<ContainerAllocator1> & lhs, const ::walker_msgs::Trk3DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.trks_list == rhs.trks_list &&
    lhs.scan == rhs.scan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::walker_msgs::Trk3DArray_<ContainerAllocator1> & lhs, const ::walker_msgs::Trk3DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace walker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::Trk3DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::Trk3DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::Trk3DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa9fb358e0c209d46c15396441e8da78";
  }

  static const char* value(const ::walker_msgs::Trk3DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa9fb358e0c209d4ULL;
  static const uint64_t static_value2 = 0x6c15396441e8da78ULL;
};

template<class ContainerAllocator>
struct DataType< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "walker_msgs/Trk3DArray";
  }

  static const char* value(const ::walker_msgs::Trk3DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"walker_msgs/Trk3D[] trks_list\n"
"\n"
"sensor_msgs/LaserScan scan\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: walker_msgs/Trk3D\n"
"float32 x\n"
"float32 y\n"
"float32 vx\n"
"float32 vy\n"
"float32 yaw\n"
"float32 radius\n"
"float32 confidence\n"
"int8 class_id\n"
"float32 dangerous\n"
"float32 x_based\n"
"float32 y_based\n"
"float32 z_based\n"
"================================================================================\n"
"MSG: sensor_msgs/LaserScan\n"
"# Single scan from a planar laser range-finder\n"
"#\n"
"# If you have another ranging device with different behavior (e.g. a sonar\n"
"# array), please find or create a different message, since applications\n"
"# will make fairly laser-specific assumptions about this data\n"
"\n"
"Header header            # timestamp in the header is the acquisition time of \n"
"                         # the first ray in the scan.\n"
"                         #\n"
"                         # in frame frame_id, angles are measured around \n"
"                         # the positive Z axis (counterclockwise, if Z is up)\n"
"                         # with zero angle being forward along the x axis\n"
"                         \n"
"float32 angle_min        # start angle of the scan [rad]\n"
"float32 angle_max        # end angle of the scan [rad]\n"
"float32 angle_increment  # angular distance between measurements [rad]\n"
"\n"
"float32 time_increment   # time between measurements [seconds] - if your scanner\n"
"                         # is moving, this will be used in interpolating position\n"
"                         # of 3d points\n"
"float32 scan_time        # time between scans [seconds]\n"
"\n"
"float32 range_min        # minimum range value [m]\n"
"float32 range_max        # maximum range value [m]\n"
"\n"
"float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n"
"float32[] intensities    # intensity data [device-specific units].  If your\n"
"                         # device does not provide intensities, please leave\n"
"                         # the array empty.\n"
;
  }

  static const char* value(const ::walker_msgs::Trk3DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.trks_list);
      stream.next(m.scan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Trk3DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walker_msgs::Trk3DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::walker_msgs::Trk3DArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trks_list[]" << std::endl;
    for (size_t i = 0; i < v.trks_list.size(); ++i)
    {
      s << indent << "  trks_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::walker_msgs::Trk3D_<ContainerAllocator> >::stream(s, indent + "    ", v.trks_list[i]);
    }
    s << indent << "scan: ";
    s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.scan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WALKER_MSGS_MESSAGE_TRK3DARRAY_H
