// Generated by gencpp from file detection_msgs/Detection2DTrig.msg
// DO NOT EDIT!


#ifndef DETECTION_MSGS_MESSAGE_DETECTION2DTRIG_H
#define DETECTION_MSGS_MESSAGE_DETECTION2DTRIG_H

#include <ros/service_traits.h>


#include <detection_msgs/Detection2DTrigRequest.h>
#include <detection_msgs/Detection2DTrigResponse.h>


namespace detection_msgs
{

struct Detection2DTrig
{

typedef Detection2DTrigRequest Request;
typedef Detection2DTrigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detection2DTrig
} // namespace detection_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detection_msgs::Detection2DTrig > {
  static const char* value()
  {
    return "0251bb8adb2f48f90dce794921ecbc66";
  }

  static const char* value(const ::detection_msgs::Detection2DTrig&) { return value(); }
};

template<>
struct DataType< ::detection_msgs::Detection2DTrig > {
  static const char* value()
  {
    return "detection_msgs/Detection2DTrig";
  }

  static const char* value(const ::detection_msgs::Detection2DTrig&) { return value(); }
};


// service_traits::MD5Sum< ::detection_msgs::Detection2DTrigRequest> should match
// service_traits::MD5Sum< ::detection_msgs::Detection2DTrig >
template<>
struct MD5Sum< ::detection_msgs::Detection2DTrigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detection_msgs::Detection2DTrig >::value();
  }
  static const char* value(const ::detection_msgs::Detection2DTrigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_msgs::Detection2DTrigRequest> should match
// service_traits::DataType< ::detection_msgs::Detection2DTrig >
template<>
struct DataType< ::detection_msgs::Detection2DTrigRequest>
{
  static const char* value()
  {
    return DataType< ::detection_msgs::Detection2DTrig >::value();
  }
  static const char* value(const ::detection_msgs::Detection2DTrigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detection_msgs::Detection2DTrigResponse> should match
// service_traits::MD5Sum< ::detection_msgs::Detection2DTrig >
template<>
struct MD5Sum< ::detection_msgs::Detection2DTrigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detection_msgs::Detection2DTrig >::value();
  }
  static const char* value(const ::detection_msgs::Detection2DTrigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_msgs::Detection2DTrigResponse> should match
// service_traits::DataType< ::detection_msgs::Detection2DTrig >
template<>
struct DataType< ::detection_msgs::Detection2DTrigResponse>
{
  static const char* value()
  {
    return DataType< ::detection_msgs::Detection2DTrig >::value();
  }
  static const char* value(const ::detection_msgs::Detection2DTrigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECTION_MSGS_MESSAGE_DETECTION2DTRIG_H
