// Generated by gencpp from file human_msgs/HumanPathArray.msg
// DO NOT EDIT!


#ifndef HUMAN_MSGS_MESSAGE_HUMANPATHARRAY_H
#define HUMAN_MSGS_MESSAGE_HUMANPATHARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <human_msgs/HumanPath.h>

namespace human_msgs
{
template <class ContainerAllocator>
struct HumanPathArray_
{
  typedef HumanPathArray_<ContainerAllocator> Type;

  HumanPathArray_()
    : header()
    , paths()  {
    }
  HumanPathArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , paths(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::human_msgs::HumanPath_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::human_msgs::HumanPath_<ContainerAllocator> >> _paths_type;
  _paths_type paths;





  typedef boost::shared_ptr< ::human_msgs::HumanPathArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_msgs::HumanPathArray_<ContainerAllocator> const> ConstPtr;

}; // struct HumanPathArray_

typedef ::human_msgs::HumanPathArray_<std::allocator<void> > HumanPathArray;

typedef boost::shared_ptr< ::human_msgs::HumanPathArray > HumanPathArrayPtr;
typedef boost::shared_ptr< ::human_msgs::HumanPathArray const> HumanPathArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_msgs::HumanPathArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_msgs::HumanPathArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_msgs::HumanPathArray_<ContainerAllocator1> & lhs, const ::human_msgs::HumanPathArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.paths == rhs.paths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_msgs::HumanPathArray_<ContainerAllocator1> & lhs, const ::human_msgs::HumanPathArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanPathArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanPathArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanPathArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanPathArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanPathArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanPathArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_msgs::HumanPathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be9631bea00a14da0ca7d5484c81b047";
  }

  static const char* value(const ::human_msgs::HumanPathArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe9631bea00a14daULL;
  static const uint64_t static_value2 = 0x0ca7d5484c81b047ULL;
};

template<class ContainerAllocator>
struct DataType< ::human_msgs::HumanPathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_msgs/HumanPathArray";
  }

  static const char* value(const ::human_msgs::HumanPathArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_msgs::HumanPathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header         header\n"
"human_msgs/HumanPath[]   paths\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: human_msgs/HumanPath\n"
"std_msgs/Header header\n"
"uint64          id\n"
"nav_msgs/Path   path\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::human_msgs::HumanPathArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_msgs::HumanPathArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanPathArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_msgs::HumanPathArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_msgs::HumanPathArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "paths[]" << std::endl;
    for (size_t i = 0; i < v.paths.size(); ++i)
    {
      s << indent << "  paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::human_msgs::HumanPath_<ContainerAllocator> >::stream(s, indent + "    ", v.paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_MSGS_MESSAGE_HUMANPATHARRAY_H
