// Generated by gencpp from file human_msgs/HumanTimeToGoal.msg
// DO NOT EDIT!


#ifndef HUMAN_MSGS_MESSAGE_HUMANTIMETOGOAL_H
#define HUMAN_MSGS_MESSAGE_HUMANTIMETOGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace human_msgs
{
template <class ContainerAllocator>
struct HumanTimeToGoal_
{
  typedef HumanTimeToGoal_<ContainerAllocator> Type;

  HumanTimeToGoal_()
    : header()
    , id(0)
    , time_to_goal()  {
    }
  HumanTimeToGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , time_to_goal()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _id_type;
  _id_type id;

   typedef ros::Duration _time_to_goal_type;
  _time_to_goal_type time_to_goal;





  typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> const> ConstPtr;

}; // struct HumanTimeToGoal_

typedef ::human_msgs::HumanTimeToGoal_<std::allocator<void> > HumanTimeToGoal;

typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoal > HumanTimeToGoalPtr;
typedef boost::shared_ptr< ::human_msgs::HumanTimeToGoal const> HumanTimeToGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_msgs::HumanTimeToGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_msgs::HumanTimeToGoal_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTimeToGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.time_to_goal == rhs.time_to_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_msgs::HumanTimeToGoal_<ContainerAllocator1> & lhs, const ::human_msgs::HumanTimeToGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53febe69f749a65c5e82fa24e0ebeaec";
  }

  static const char* value(const ::human_msgs::HumanTimeToGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53febe69f749a65cULL;
  static const uint64_t static_value2 = 0x5e82fa24e0ebeaecULL;
};

template<class ContainerAllocator>
struct DataType< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_msgs/HumanTimeToGoal";
  }

  static const char* value(const ::human_msgs::HumanTimeToGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint64          id\n"
"duration        time_to_goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::human_msgs::HumanTimeToGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.time_to_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanTimeToGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_msgs::HumanTimeToGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_msgs::HumanTimeToGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    s << indent << "time_to_goal: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.time_to_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_MSGS_MESSAGE_HUMANTIMETOGOAL_H
