// Generated by gencpp from file human_msgs/TrackedHumanArray.msg
// DO NOT EDIT!


#ifndef HUMAN_MSGS_MESSAGE_TRACKEDHUMANARRAY_H
#define HUMAN_MSGS_MESSAGE_TRACKEDHUMANARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <human_msgs/TrackedHuman.h>

namespace human_msgs
{
template <class ContainerAllocator>
struct TrackedHumanArray_
{
  typedef TrackedHumanArray_<ContainerAllocator> Type;

  TrackedHumanArray_()
    : header()
    , humans()  {
    }
  TrackedHumanArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , humans(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::human_msgs::TrackedHuman_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::human_msgs::TrackedHuman_<ContainerAllocator> >> _humans_type;
  _humans_type humans;





  typedef boost::shared_ptr< ::human_msgs::TrackedHumanArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_msgs::TrackedHumanArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedHumanArray_

typedef ::human_msgs::TrackedHumanArray_<std::allocator<void> > TrackedHumanArray;

typedef boost::shared_ptr< ::human_msgs::TrackedHumanArray > TrackedHumanArrayPtr;
typedef boost::shared_ptr< ::human_msgs::TrackedHumanArray const> TrackedHumanArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_msgs::TrackedHumanArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::human_msgs::TrackedHumanArray_<ContainerAllocator1> & lhs, const ::human_msgs::TrackedHumanArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.humans == rhs.humans;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::human_msgs::TrackedHumanArray_<ContainerAllocator1> & lhs, const ::human_msgs::TrackedHumanArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace human_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_msgs::TrackedHumanArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_msgs::TrackedHumanArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_msgs::TrackedHumanArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddb513d4fa77f778f04463ac24f9c5a4";
  }

  static const char* value(const ::human_msgs::TrackedHumanArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddb513d4fa77f778ULL;
  static const uint64_t static_value2 = 0xf04463ac24f9c5a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_msgs/TrackedHumanArray";
  }

  static const char* value(const ::human_msgs::TrackedHumanArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header              header\n"
"TrackedHuman[]      humans\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: human_msgs/TrackedHuman\n"
"# states\n"
"int8 STATIC=0\n"
"int8 MOVING=1\n"
"int8 STOPPED=2\n"
"int8 BLOCKED=3\n"
"\n"
"uint64              track_id\n"
"int8                state\n"
"TrackedSegment[]    segments\n"
"\n"
"================================================================================\n"
"MSG: human_msgs/TrackedSegment\n"
"int8                                type\n"
"geometry_msgs/PoseWithCovariance    pose\n"
"geometry_msgs/TwistWithCovariance   twist\n"
"geometry_msgs/AccelWithCovariance   accel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/AccelWithCovariance\n"
"# This expresses acceleration in free space with uncertainty.\n"
"\n"
"Accel accel\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
;
  }

  static const char* value(const ::human_msgs::TrackedHumanArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.humans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedHumanArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_msgs::TrackedHumanArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_msgs::TrackedHumanArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "humans[]" << std::endl;
    for (size_t i = 0; i < v.humans.size(); ++i)
    {
      s << indent << "  humans[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::human_msgs::TrackedHuman_<ContainerAllocator> >::stream(s, indent + "    ", v.humans[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_MSGS_MESSAGE_TRACKEDHUMANARRAY_H
