(cl:defpackage walker_msgs-srv
  (:use )
  (:export
   "DETECTION2DTRIGGER"
   "<DETECTION2DTRIGGER-REQUEST>"
   "DETECTION2DTRIGGER-REQUEST"
   "<DETECTION2DTRIGGER-RESPONSE>"
   "DETECTION2DTRIGGER-RESPONSE"
   "PUSHINGACTIONTRIGGER"
   "<PUSHINGACTIONTRIGGER-REQUEST>"
   "PUSHINGACTIONTRIGGER-REQUEST"
   "<PUSHINGACTIONTRIGGER-RESPONSE>"
   "PUSHINGACTIONTRIGGER-RESPONSE"
  ))

