// Generated by gencpp from file detection_msgs/Det3D.msg
// DO NOT EDIT!


#ifndef DETECTION_MSGS_MESSAGE_DET3D_H
#define DETECTION_MSGS_MESSAGE_DET3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection_msgs
{
template <class ContainerAllocator>
struct Det3D_
{
  typedef Det3D_<ContainerAllocator> Type;

  Det3D_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , radius(0.0)
    , confidence(0.0)
    , place(0)
    , class_name()
    , class_id(0)
    , height(0.0)
    , width(0.0)
    , length(0.0)  {
    }
  Det3D_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , radius(0.0)
    , confidence(0.0)
    , place(0)
    , class_name(_alloc)
    , class_id(0)
    , height(0.0)
    , width(0.0)
    , length(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int8_t _place_type;
  _place_type place;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef int8_t _class_id_type;
  _class_id_type class_id;

   typedef float _height_type;
  _height_type height;

   typedef float _width_type;
  _width_type width;

   typedef float _length_type;
  _length_type length;





  typedef boost::shared_ptr< ::detection_msgs::Det3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection_msgs::Det3D_<ContainerAllocator> const> ConstPtr;

}; // struct Det3D_

typedef ::detection_msgs::Det3D_<std::allocator<void> > Det3D;

typedef boost::shared_ptr< ::detection_msgs::Det3D > Det3DPtr;
typedef boost::shared_ptr< ::detection_msgs::Det3D const> Det3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection_msgs::Det3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection_msgs::Det3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detection_msgs::Det3D_<ContainerAllocator1> & lhs, const ::detection_msgs::Det3D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw &&
    lhs.radius == rhs.radius &&
    lhs.confidence == rhs.confidence &&
    lhs.place == rhs.place &&
    lhs.class_name == rhs.class_name &&
    lhs.class_id == rhs.class_id &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.length == rhs.length;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detection_msgs::Det3D_<ContainerAllocator1> & lhs, const ::detection_msgs::Det3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detection_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detection_msgs::Det3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_msgs::Det3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_msgs::Det3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_msgs::Det3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_msgs::Det3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_msgs::Det3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection_msgs::Det3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "faf9ea4ce475ae1fc02d423888a2664b";
  }

  static const char* value(const ::detection_msgs::Det3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfaf9ea4ce475ae1fULL;
  static const uint64_t static_value2 = 0xc02d423888a2664bULL;
};

template<class ContainerAllocator>
struct DataType< ::detection_msgs::Det3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection_msgs/Det3D";
  }

  static const char* value(const ::detection_msgs::Det3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection_msgs::Det3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 yaw\n"
"float32 radius\n"
"float32 confidence\n"
"int8 place\n"
"string class_name\n"
"int8 class_id\n"
"\n"
"float32 height\n"
"float32 width\n"
"float32 length\n"
;
  }

  static const char* value(const ::detection_msgs::Det3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection_msgs::Det3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.radius);
      stream.next(m.confidence);
      stream.next(m.place);
      stream.next(m.class_name);
      stream.next(m.class_id);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Det3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection_msgs::Det3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection_msgs::Det3D_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "place: ";
    Printer<int8_t>::stream(s, indent + "  ", v.place);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "class_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_MSGS_MESSAGE_DET3D_H
