// Generated by gencpp from file pedsim_srvs/GymReset.msg
// DO NOT EDIT!


#ifndef PEDSIM_SRVS_MESSAGE_GYMRESET_H
#define PEDSIM_SRVS_MESSAGE_GYMRESET_H

#include <ros/service_traits.h>


#include <pedsim_srvs/GymResetRequest.h>
#include <pedsim_srvs/GymResetResponse.h>


namespace pedsim_srvs
{

struct GymReset
{

typedef GymResetRequest Request;
typedef GymResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GymReset
} // namespace pedsim_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pedsim_srvs::GymReset > {
  static const char* value()
  {
    return "a97915fd01741ae65f8ce47a0e7cc85c";
  }

  static const char* value(const ::pedsim_srvs::GymReset&) { return value(); }
};

template<>
struct DataType< ::pedsim_srvs::GymReset > {
  static const char* value()
  {
    return "pedsim_srvs/GymReset";
  }

  static const char* value(const ::pedsim_srvs::GymReset&) { return value(); }
};


// service_traits::MD5Sum< ::pedsim_srvs::GymResetRequest> should match
// service_traits::MD5Sum< ::pedsim_srvs::GymReset >
template<>
struct MD5Sum< ::pedsim_srvs::GymResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pedsim_srvs::GymReset >::value();
  }
  static const char* value(const ::pedsim_srvs::GymResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pedsim_srvs::GymResetRequest> should match
// service_traits::DataType< ::pedsim_srvs::GymReset >
template<>
struct DataType< ::pedsim_srvs::GymResetRequest>
{
  static const char* value()
  {
    return DataType< ::pedsim_srvs::GymReset >::value();
  }
  static const char* value(const ::pedsim_srvs::GymResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pedsim_srvs::GymResetResponse> should match
// service_traits::MD5Sum< ::pedsim_srvs::GymReset >
template<>
struct MD5Sum< ::pedsim_srvs::GymResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pedsim_srvs::GymReset >::value();
  }
  static const char* value(const ::pedsim_srvs::GymResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pedsim_srvs::GymResetResponse> should match
// service_traits::DataType< ::pedsim_srvs::GymReset >
template<>
struct DataType< ::pedsim_srvs::GymResetResponse>
{
  static const char* value()
  {
    return DataType< ::pedsim_srvs::GymReset >::value();
  }
  static const char* value(const ::pedsim_srvs::GymResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEDSIM_SRVS_MESSAGE_GYMRESET_H
