(cl:in-package path_assessment-msg)
(cl:export '(HEADER-VAL
          HEADER
          STOP-VAL
          STOP
          T-VAL
          T
          ROBOT_X-VAL
          ROBOT_X
          ROBOT_Y-VAL
          ROBOT_Y
          EVA_CUR_H-VAL
          EVA_CUR_H
          IDX_H-VAL
          IDX_H
          EVA_AVG_H-VAL
          EVA_AVG_H
          COLLI_T_H-VAL
          COLLI_T_H
          COLLI_H-VAL
          COLLI_H
          EVA_CUR_O-VAL
          EVA_CUR_O
          IDX_O-VAL
          IDX_O
          EVA_AVG_O-VAL
          EVA_AVG_O
          COLLI_T_O-VAL
          COLLI_T_O
          COLLI_O-VAL
          COLLI_O
))