(cl:in-package walker_msgs-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          YAW-VAL
          YAW
          RADIUS-VAL
          RADIUS
          CONFIDENCE-VAL
          CONFIDENCE
          CLASS_NAME-VAL
          CLASS_NAME
          CLASS_ID-VAL
          CLASS_ID
          X_BASED-VAL
          X_BASED
          Y_BASED-VAL
          Y_BASED
          Z_BASED-VAL
          Z_BASED
          H-VAL
          H
          W-VAL
          W
          L-VAL
          L
))