// Generated by gencpp from file pedsim_msgs/GymAgentInfo.msg
// DO NOT EDIT!


#ifndef PEDSIM_MSGS_MESSAGE_GYMAGENTINFO_H
#define PEDSIM_MSGS_MESSAGE_GYMAGENTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace pedsim_msgs
{
template <class ContainerAllocator>
struct GymAgentInfo_
{
  typedef GymAgentInfo_<ContainerAllocator> Type;

  GymAgentInfo_()
    : init_pose2d()
    , waypoints_list()  {
    }
  GymAgentInfo_(const ContainerAllocator& _alloc)
    : init_pose2d(_alloc)
    , waypoints_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _init_pose2d_type;
  _init_pose2d_type init_pose2d;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _waypoints_list_type;
  _waypoints_list_type waypoints_list;





  typedef boost::shared_ptr< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GymAgentInfo_

typedef ::pedsim_msgs::GymAgentInfo_<std::allocator<void> > GymAgentInfo;

typedef boost::shared_ptr< ::pedsim_msgs::GymAgentInfo > GymAgentInfoPtr;
typedef boost::shared_ptr< ::pedsim_msgs::GymAgentInfo const> GymAgentInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator1> & lhs, const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator2> & rhs)
{
  return lhs.init_pose2d == rhs.init_pose2d &&
    lhs.waypoints_list == rhs.waypoints_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator1> & lhs, const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pedsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c16d0b53f72a3ed400f25f621b18ae2";
  }

  static const char* value(const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c16d0b53f72a3edULL;
  static const uint64_t static_value2 = 0x400f25f621b18ae2ULL;
};

template<class ContainerAllocator>
struct DataType< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pedsim_msgs/GymAgentInfo";
  }

  static const char* value(const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D    init_pose2d\n"
"geometry_msgs/Pose2D[]  waypoints_list\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.init_pose2d);
      stream.next(m.waypoints_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GymAgentInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pedsim_msgs::GymAgentInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pedsim_msgs::GymAgentInfo_<ContainerAllocator>& v)
  {
    s << indent << "init_pose2d: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.init_pose2d);
    s << indent << "waypoints_list[]" << std::endl;
    for (size_t i = 0; i < v.waypoints_list.size(); ++i)
    {
      s << indent << "  waypoints_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEDSIM_MSGS_MESSAGE_GYMAGENTINFO_H
